### ISSUE TITLE
Use/import a Versioned Model

### ISSUE THREAD

**Issue by kvan1** [CymaLtd/ArchiGITPlugin#16]
Hi 

Thanks for the great work on an important plugin!

I'm probably missing something, but when I try to **Import Versioned Model**, all the git operations are fine and the directory fills with repo contents. The only problem is that no model is read into Archi?

After entering the **Remote Repository Information** dialog, the **Models** window in Archi takes focus as if it would have received a new model, but there is no file tree, contents or diagrams -just empty.

Am I missing some final step for import?

Best,
Kevin

_Tested with Archi v2.7.1 & plugin v2.7.1.2 on Windows XP, 7 & Ubuntu_
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/198378/2851795/13d3de56-d123-11e3-8031-9df3ab219ed7.png)

**Comment by mjtapp** [comment]
Hi Kevin,

If you aren't getting a model, but the directory has the git files, then
chance are that the importer is getting some kind of error that it's not
showing you. I have to admit that unexpected runtime errors is something
it's not handling very well at the moment. I've had it happen once or
twice, but I have the source and run and debug mode to see what is going
on, you probably don't have that luxury. It is definitely something I need
to fix.

If your model is not sensitive, feel free to send me the .archimate file
and I'll try it at my end and see what the issue is.

Michael

On 1 May 2014 23:31, Kevin notifications@github.com wrote:

> Hi
> 
> Thanks for the great work on an important plugin!
> 
> I'm probably missing something, but when I try to _Import Versioned Model_,
> all the git operations are fine and the directory fills with repo contents.
> The only problem is that no model is read into Archi?
> 
> After entering the _Remote Repository Information_ dialog, the _Models_window in Archi takes focus as if it would have received a new model, but
> there is no file tree, contents or diagrams -just empty.
> 
> Am I missing some final step for import?
> 
> Best,
> Kevin
> 
> _Tested with Archi v2.7.1 & plugin v2.7.1.2 on Windows XP, 7 & Ubuntu_
> Screenshot
> 
> [image: image]https://cloud.githubusercontent.com/assets/198378/2851795/13d3de56-d123-11e3-8031-9df3ab219ed7.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CymaLtd/ArchiGITPlugin/issues/16
> .

## 

  Michael Tapp, Principal Architect

*email: *michael@cyma.co.nz
*phone: *021 484 196

**Comment by kvan1** [comment]
Hey - thanks for the offer!
The model is not sensitive -it's mostly just a POC test. The repo is here:
https://github.com/kvan1/RSDEAtest1/tree/main

Let me know what you find - I may have to install Eclipse and get some
plugin dev going ;-)

Best
/Kevin

Kevin

_http://about.me/kevindonovan http://about.me/kevindonovan_

**Comment by mjtapp** [comment]
Hi Kevin,

I believe I have found the problem, but I need to figure out the right fix.
The issue is in the YAML parser where it is throwing an exception when it
is trying to parse one of the files. Looking at the file and playing with
it a bit, I believe the issue has to do with UTF encoding as the specific
one it is crashing on has a non-english character in it and when I remove
it, it parses it OK before it stops the next time it finds one.

According to the snakeYAML documentation it should pick up the right
encoding and deal with it properly, but that doesn't seem to be the case so
I'll have to figure out why and how to get around it I'm afraid. I'll log
it as an issue and see if I can figure out an answer/workaround over the
next week or so.

Thanks for the testing :)

Michael

On 7 May 2014 01:58, Kevin notifications@github.com wrote:

> Hey - thanks for the offer!
> The model is not sensitive -it's mostly just a POC test. The repo is here:
> https://github.com/kvan1/RSDEAtest1/tree/main
> 
> Let me know what you find - I may have to install Eclipse and get some
> plugin dev going ;-)
> 
> Best
> /Kevin
> 
> Kevin
> 
> _http://about.me/kevindonovan http://about.me/kevindonovan_
> 
> On Thu, May 1, 2014 at 10:53 PM, mjtapp notifications@github.com wrote:
> 
> > Hi Kevin,
> > 
> > If you aren't getting a model, but the directory has the git files, then
> > chance are that the importer is getting some kind of error that it's not
> > showing you. I have to admit that unexpected runtime errors is something
> > it's not handling very well at the moment. I've had it happen once or
> > twice, but I have the source and run and debug mode to see what is going
> > on, you probably don't have that luxury. It is definitely something I
> > need
> > to fix.
> > 
> > If your model is not sensitive, feel free to send me the .archimate file
> > and I'll try it at my end and see what the issue is.
> > 
> > Michael
> > 
> > On 1 May 2014 23:31, Kevin notifications@github.com wrote:
> > 
> > > Hi
> > > 
> > > Thanks for the great work on an important plugin!
> > > 
> > > I'm probably missing something, but when I try to _Import Versioned
> > > Model_,
> > > all the git operations are fine and the directory fills with repo
> > > contents.
> > > The only problem is that no model is read into Archi?
> > > 
> > > After entering the _Remote Repository Information_ dialog, the
> > > _Models_window in Archi takes focus as if it would have received a new
> > > model, but
> > > there is no file tree, contents or diagrams -just empty.
> > > 
> > > Am I missing some final step for import?
> > > 
> > > Best,
> > > Kevin
> > > 
> > > _Tested with Archi v2.7.1 & plugin v2.7.1.2 on Windows XP, 7 & Ubuntu_
> > > Screenshot
> > > 
> > > [image: image]<
> > 
> > https://cloud.githubusercontent.com/assets/198378/2851795/13d3de56-d123-11e3-8031-9df3ab219ed7.png>
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/CymaLtd/ArchiGITPlugin/issues/16>
> > > .
> > 
> > ## 
> > 
> > Michael Tapp, Principal Architect
> > 
> > *email: *michael@cyma.co.nz
> > *phone: *021 484 196
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/CymaLtd/ArchiGITPlugin/issues/16#issuecomment-41955595>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CymaLtd/ArchiGITPlugin/issues/16#issuecomment-42304952
> .

## 

  Michael Tapp, Principal Architect

*email: *michael@cyma.co.nz
*phone: *021 484 196

**Comment by mjtapp** [comment]
Hi Kevin,

I've put a fix in the plugin that will hopefully address your issue,
although I can't be sure. To explain, I think the issue is with the export
not correctly outputting the yaml files in UTF-8, but I think it might be
related to JVM because I couldn't duplicate it myself.

I've made a change anyway to force the yaml files to be written in UTF-8
now so if that was the problem, it should be fixed in the release I've just
made.

So if you're interested in testing it, pick up the new release, open your
model in the normal way, re-export it and then try the import. Hopefully
the issue will be fixed the import will complete without a problem.

Michael

On 7 May 2014 18:28, Michael Tapp michael@cyma.co.nz wrote:

> Hi Kevin,
> 
> I believe I have found the problem, but I need to figure out the right
> fix. The issue is in the YAML parser where it is throwing an exception when
> it is trying to parse one of the files. Looking at the file and playing
> with it a bit, I believe the issue has to do with UTF encoding as the
> specific one it is crashing on has a non-english character in it and when I
> remove it, it parses it OK before it stops the next time it finds one.
> 
> According to the snakeYAML documentation it should pick up the right
> encoding and deal with it properly, but that doesn't seem to be the case so
> I'll have to figure out why and how to get around it I'm afraid. I'll log
> it as an issue and see if I can figure out an answer/workaround over the
> next week or so.
> 
> Thanks for the testing :)
> 
> Michael
> 
> On 7 May 2014 01:58, Kevin notifications@github.com wrote:
> 
> > Hey - thanks for the offer!
> > The model is not sensitive -it's mostly just a POC test. The repo is
> > here:
> > https://github.com/kvan1/RSDEAtest1/tree/main
> > 
> > Let me know what you find - I may have to install Eclipse and get some
> > plugin dev going ;-)
> > 
> > Best
> > /Kevin
> > 
> > Kevin
> > 
> > _http://about.me/kevindonovan http://about.me/kevindonovan_
> > 
> > On Thu, May 1, 2014 at 10:53 PM, mjtapp notifications@github.com
> > wrote:
> > 
> > > Hi Kevin,
> > > 
> > > If you aren't getting a model, but the directory has the git files,
> > > then
> > > chance are that the importer is getting some kind of error that it's
> > > not
> > > showing you. I have to admit that unexpected runtime errors is
> > > something
> > > it's not handling very well at the moment. I've had it happen once or
> > > twice, but I have the source and run and debug mode to see what is
> > > going
> > > on, you probably don't have that luxury. It is definitely something I
> > > need
> > > to fix.
> > > 
> > > If your model is not sensitive, feel free to send me the .archimate
> > > file
> > > and I'll try it at my end and see what the issue is.
> > > 
> > > Michael
> > > 
> > > On 1 May 2014 23:31, Kevin notifications@github.com wrote:
> > > 
> > > > Hi
> > > > 
> > > > Thanks for the great work on an important plugin!
> > > > 
> > > > I'm probably missing something, but when I try to _Import Versioned
> > > > Model_,
> > > > all the git operations are fine and the directory fills with repo
> > > > contents.
> > > > The only problem is that no model is read into Archi?
> > > > 
> > > > After entering the _Remote Repository Information_ dialog, the
> > > > _Models_window in Archi takes focus as if it would have received a new
> > > > model, but
> > > > there is no file tree, contents or diagrams -just empty.
> > > > 
> > > > Am I missing some final step for import?
> > > > 
> > > > Best,
> > > > Kevin
> > > > 
> > > > _Tested with Archi v2.7.1 & plugin v2.7.1.2 on Windows XP, 7 &
> > > > Ubuntu_
> > > > Screenshot
> > > > 
> > > > [image: image]<
> > > 
> > > https://cloud.githubusercontent.com/assets/198378/2851795/13d3de56-d123-11e3-8031-9df3ab219ed7.png>
> > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/CymaLtd/ArchiGITPlugin/issues/16>
> > > > .
> > > 
> > > ## 
> > > 
> > > Michael Tapp, Principal Architect
> > > 
> > > *email: *michael@cyma.co.nz
> > > *phone: *021 484 196
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/CymaLtd/ArchiGITPlugin/issues/16#issuecomment-41955595>
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/CymaLtd/ArchiGITPlugin/issues/16#issuecomment-42304952
> > .
> 
> ## 
> 
>   Michael Tapp, Principal Architect
> 
> *email: *michael@cyma.co.nz
> *phone: *021 484 196

## 

  Michael Tapp, Principal Architect

*email: *michael@cyma.co.nz
*phone: *021 484 196
